version: '3.8'

services:

  user-db:
    image: postgres:15
    container_name: ecommerce-user
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_USER}:5432"
    volumes:
      - user-data:/var/lib/postgresql/data

  product-db:
    image: postgres:15
    container_name: ecommerce-product
    environment:
      POSTGRES_DB: ${PRODUCT_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_PRODUCT}:5432"
    volumes:
      - product-data:/var/lib/postgresql/data

  order-db:
    image: postgres:15
    container_name: ecommerce-order
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_ORDER}:5432"
    volumes:
      - order-data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: ecommerce-mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce-rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  user-data:
  product-data:
  order-data:
  mongo-data:
  rabbitmq-data: