name: Build Microservices

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build api-gateway
        run: |
          cd api-gateway
          mvn clean install

      - name: Build user-service
        run: |
          cd user-service
          mvn clean install

      - name: Build product-service
        run: |
          cd product-service
          mvn clean install

      - name: Build order-service
        run: |
          cd order-service
          mvn clean install
