name: Build Microservices

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      api_gateway: ${{ steps.filter.outputs.api_gateway }}
      user_service: ${{ steps.filter.outputs.user_service }}
      product_service: ${{ steps.filter.outputs.product_service }}
      order_service: ${{ steps.filter.outputs.order_service }}

    steps:

      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api_gateway:
              - 'api-gateway/**'
            user_service:
              - 'user-service/**'
            product_service:
              - 'product-service/**'
            order_service:
              - 'order-service/**'

  build-api-gateway:
    needs: detect-changes
    if: needs.detect-changes.outputs.api_gateway == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Build api-gateway
        run: |
          cd api-gateway
          mvn clean install

  build-user-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.user_service == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

       - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Build user-service
        run: |
          cd user-service
          mvn clean install

  build-product-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.product_service == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

       - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Build product-service
        run: |
          cd product-service
          mvn clean install

  build-order-service:
    needs: detect-changes
    if: needs.detect-changes.outputs.order_service == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

       - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Build order-service
        run: |
          cd order-service
          mvn clean install
